import Head from 'next/head'
import { Inter } from '@next/font/google'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram} from 'react-icons/ai'
import Image from "next/image"
import myPic from '../public/myPic.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Kannan Jayachandran Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
     <section className='min-h-screen'>
      <nav className='py-10 mb-12 flex justify-between'>
        <h1 className='text-xl font-burtons'>Kannan Jayachandran</h1>
        <ul className='flex items-center'>
          <li>
            <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
          </li>
          <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 rounded-md ml-8' href="#">Resume</a></li>
        </ul>
      </nav>
      <div className='text-center p-10'>
        <h3 className='text-3xl py-2 font-medium'>I am</h3>
        <h2 className='text-5xl py-2 text-teal-600 font-medium'>Kannan Jayachandran</h2>
        <h3 className='text-xl py-2 font-medium'>Aspiring data scientist</h3>
      </div>

      <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>

        <AiFillTwitterCircle/>
        <AiFillLinkedin/>
        <AiFillInstagram/>
      </div>

      <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
        <Image className='absolute h-full w-full ' alt="Description of the image" src={myPic} />
      </div>
     </section>

{/* Section 2 */}

    <section>
      <div>
        <h3 className='text-3xl py-1'>Personal Details</h3>

        <p className='text-md py-2 leading-8 text-gray-800'>
        I am <span className='text-teal-500'>Kannan Jayachandran</span> and I am a Computer Science 
        Engineering student from India specializing in <span className='text-teal-500'>Artificial 
        Intelligence</span> & <span className='text-teal-500'>Machine Learning.</span> 
        I am currently in the pre-final year of my Bachelor&apos;s degree in Technology program. 
        My passion for learning new things and sharing my knowledge drives me to spend a great deal 
        of time learning concepts of computer science in depth. I&apos;m looking forward to pursue 
        a career in <span className='text-teal-500'>data science </span>and 
        <span className='text-teal-500'>machine learning</span>.
        
        </p>
        <p className='text-md py-2 leading-8 text-gray-800'>
        My interests outside of Computer Science include reading Sci-Fi books, exploring Physics, 
        and studying History. I also enjoy watching movies.
        </p>
      </div>

      <div>
        
      </div>
    </section>

      </main>
    </>
  )
}
